/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.youtube;

/**
 *
 * @author brand
 */
public class Edit_user extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Edit_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        background = new javax.swing.JPanel();
        icon_home = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        field_username = new javax.swing.JTextField();
        label_username = new javax.swing.JLabel();
        btn_confirm_edit_user = new javax.swing.JButton();
        btn_upload_image_user = new javax.swing.JButton();
        label_imagen_user = new javax.swing.JLabel();
        field_password = new javax.swing.JTextField();
        label_password = new javax.swing.JLabel();
        field_confirm_password = new javax.swing.JTextField();
        label_confirm_password = new javax.swing.JLabel();
        icon_user = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");
        popupMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupMenu1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1080, 720));

        background.setBackground(new java.awt.Color(2, 30, 26));
        background.setMaximumSize(new java.awt.Dimension(1080, 720));
        background.setMinimumSize(new java.awt.Dimension(1080, 720));

        icon_home.setIcon(new javax.swing.ImageIcon("D:\\Programacion\\programacion-integrativa\\src\\main\\java\\icons\\casa.png")); // NOI18N
        icon_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redirect_icon_home(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(8, 63, 55));
        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 94, 93));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 110));

        field_username.setBackground(new java.awt.Color(6, 137, 137));
        field_username.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        field_username.setForeground(new java.awt.Color(203, 203, 203));
        field_username.setText("Username");
        field_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        field_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(field_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 380, 60));

        label_username.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        label_username.setForeground(new java.awt.Color(203, 203, 203));
        label_username.setText("Username");
        jPanel1.add(label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 70, 20));

        btn_confirm_edit_user.setBackground(new java.awt.Color(63, 225, 176));
        btn_confirm_edit_user.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        btn_confirm_edit_user.setForeground(new java.awt.Color(255, 255, 255));
        btn_confirm_edit_user.setText("Confirmar");
        btn_confirm_edit_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirm_edit_userbtn_create_acc(evt);
            }
        });
        jPanel1.add(btn_confirm_edit_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 230, 60));

        btn_upload_image_user.setBackground(new java.awt.Color(63, 225, 176));
        btn_upload_image_user.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 16)); // NOI18N
        btn_upload_image_user.setForeground(new java.awt.Color(255, 255, 255));
        btn_upload_image_user.setText("Cargar Imagen");
        btn_upload_image_user.setMaximumSize(new java.awt.Dimension(151, 35));
        btn_upload_image_user.setMinimumSize(new java.awt.Dimension(151, 35));
        btn_upload_image_user.setPreferredSize(new java.awt.Dimension(151, 35));
        btn_upload_image_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_upload_image_userbtn_create_acc(evt);
            }
        });
        jPanel1.add(btn_upload_image_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 151, 35));

        label_imagen_user.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        label_imagen_user.setForeground(new java.awt.Color(203, 203, 203));
        label_imagen_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_imagen_user.setText("Imagen");
        jPanel1.add(label_imagen_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 150, 20));

        field_password.setBackground(new java.awt.Color(6, 137, 137));
        field_password.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        field_password.setForeground(new java.awt.Color(203, 203, 203));
        field_password.setText("Contraseña");
        field_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        field_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(field_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 380, 60));

        label_password.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        label_password.setForeground(new java.awt.Color(203, 203, 203));
        label_password.setText("Contraseña");
        jPanel1.add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 110, 20));

        field_confirm_password.setBackground(new java.awt.Color(6, 137, 137));
        field_confirm_password.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        field_confirm_password.setForeground(new java.awt.Color(203, 203, 203));
        field_confirm_password.setText("Confirmar Contraseña");
        field_confirm_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        field_confirm_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_confirm_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(field_confirm_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 380, 60));

        label_confirm_password.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        label_confirm_password.setForeground(new java.awt.Color(203, 203, 203));
        label_confirm_password.setText("Confirmar Contraseña");
        jPanel1.add(label_confirm_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 160, 20));

        icon_user.setIcon(new javax.swing.ImageIcon("D:\\Programacion\\programacion-integrativa\\src\\main\\java\\icons\\user.png")); // NOI18N
        jPanel1.add(icon_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 300, 300));

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(icon_home, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(icon_home))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_usernameActionPerformed

    private void redirect_icon_home(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redirect_icon_home
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_redirect_icon_home

    private void btn_confirm_edit_userbtn_create_acc(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirm_edit_userbtn_create_acc
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_confirm_edit_userbtn_create_acc

    private void btn_upload_image_userbtn_create_acc(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_upload_image_userbtn_create_acc
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_upload_image_userbtn_create_acc

    private void field_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_passwordActionPerformed

    private void field_confirm_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_confirm_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_confirm_passwordActionPerformed

    private void popupMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popupMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btn_confirm_edit_user;
    private javax.swing.JButton btn_upload_image_user;
    private javax.swing.JTextField field_confirm_password;
    private javax.swing.JTextField field_password;
    private javax.swing.JTextField field_username;
    private javax.swing.JLabel icon_home;
    private javax.swing.JLabel icon_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_confirm_password;
    private javax.swing.JLabel label_imagen_user;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_username;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
